import request from './request'

export const listOrders = params => request.get('/orders', { params })
export const getOrder = id => request.get(`/orders/${id}`)
export const getOrderByOrderNo = orderNo => request.get(`/orders/no/${orderNo}`)
export const checkin = data => request.post('/orders/checkin', data)
export const checkout = (id, data) => request.post(`/orders/${id}/checkout`, data)
export const cancelOrder = id => request.post(`/orders/${id}/cancel`)
export const settlePending = id => request.post(`/orders/${id}/settle`)
export const orderStats = params => request.get('/orders/stats', { params })
export const extendStay = (id, data) => request.post(`/orders/${id}/extend`, data)
export const changeRoom = (id, data) => request.post(`/orders/${id}/change-room`, data)
export const todayArrivals = () => request.get('/orders/today-arrivals')
export const todayDepartures = () => request.get('/orders/today-departures')
export const customerOrders = customerId => request.get(`/orders/customer/${customerId}`)
export const lowDepositOrders = () => request.get('/orders/low-deposit')
export const recommendRooms = params => request.get('/orders/recommend-rooms', { params })
export const getOrderItems = orderId => request.get(`/orders/${orderId}/items`)
export const addOrderItem = (orderId, data) => request.post(`/orders/${orderId}/items`, data)
export const deleteOrderItem = (orderId, itemId) => request.delete(`/orders/${orderId}/items/${itemId}`)
